apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        # readinessProbe:      
        #   httpGet:
        #     path: /healthz            
        #     port: 80
        #   initialDelaySeconds: 15     
        #   periodSeconds: 10           
