name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t my-tyk -f golang/dockerfile ./golang

      - name: Tag Docker image
        run: docker tag my-tyk ${{ secrets.DOCKER_USERNAME }}/my-tyk:latest

      - name: Scan Docker image
        uses: snyk/actions/docker@master
        continue-on-error: true
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/my-tyk:latest 
          args: --file=Dockerfile --severity-threshold=high --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Push Docker image (if scan passes) 
        run: |
          if [[ $? -eq 0 ]]; then
            docker push ${{ secrets.DOCKER_USERNAME }}/my-tyk:latest
          fi

      - name: Upload Snyk report as sarif 📦
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      

      # - name: Push Docker image
      #   run: docker push ${{ secrets.DOCKER_USERNAME }}/my-tyk:latest
